#!/usr/bin/env python3
"""The regulatory corpus: generated from the contract set, never hand-maintained.

This exists because the regulatory Knowledge Base was created with no data source at all.
Terraform applied cleanly, `kb-sync.sh` iterated its (empty) data-source list and passed, and
`search_regulation` returned nothing forever — a tool that is present, authorized, invoked
and useless, with no error anywhere.

What is generated here is an **index**, not the regulation. Each entry names the clause a
datapoint discharges, what the clause requires of the undertaking, the unit and boundary the
disclosure carries, and the conditions under which it may lawfully be omitted. The
authoritative text is the Official Journal; loading a licensed copy of it alongside this
index is a documented ingest step (`docs/DAY-ONE.md`) and not something this repository
invents.

Generating it from `contracts/` rather than writing it by hand is the same decision as
everywhere else in this project: the index and the datapoints cannot drift, because there is
only one of them. A datapoint added without a corpus entry would otherwise be a datapoint the
model can never find guidance for.

Usage:
    python pipelines/ingest/regulatory.py             # regenerate corpus/regulatory/
    python pipelines/ingest/regulatory.py --check     # fail if it is stale (CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

from attestor.contracts import loader, reason_codes
from attestor.contracts.model import DatapointContract

ROOT = Path(__file__).resolve().parents[2]
CORPUS = ROOT / "corpus" / "regulatory"

README = """# Regulatory corpus

Generated by `pipelines/ingest/regulatory.py` from `contracts/`. Do not edit by hand — a
change here is a change to a datapoint contract.

Each file is an **index entry** for one clause: what it asks for, in what unit, over what
consolidation boundary, and which omissions the standard permits. It is deliberately not a
copy of the regulation. The authoritative text of the ESRS Delegated Regulation and of
Regulation (EU) 2024/1689 is the Official Journal, and loading it into this corpus alongside
the index is a documented ingest step rather than something this repository reproduces.

The corpus is shared across tenants and carries no tenant metadata. That is why it lives
under the `_shared/` prefix: a tenant id must start with a letter, so no tenant can ever be
allocated a prefix that collides with it.
"""


def _entry(contract: DatapointContract) -> str:
    omissions = [
        f"- `{code}` — {reason_codes.resolve(code).summary} ({reason_codes.resolve(code).basis})"
        for code in contract.abstention.allowed_reasons
    ]
    lines = [
        f"# {contract.reference} — {contract.title}",
        "",
        f"- **standard**: {contract.standard.value} ({contract.standard_version})",
        f"- **datapoint**: `{contract.id}`",
        f"- **kind**: {contract.kind.value}",
        f"- **reporting period basis**: {contract.period.value}",
    ]
    if contract.unit:
        lines.append(f"- **unit**: {contract.unit} (published to {contract.precision} dp)")
    if contract.boundary.value != "not_applicable":
        lines.append(f"- **consolidation boundary**: {contract.boundary.value}")
    lines += ["", "## What the clause requires", "", contract.description.strip() or contract.title]
    if contract.methodology.strip():
        lines += ["", "## Methodology as declared", "", contract.methodology.strip()]
    lines += [
        "",
        "## Evidence the undertaking must hold",
        "",
        (
            "Inherited from the components of this figure."
            if contract.evidence.inherited
            else (
                "Documents of class "
                + ", ".join(f"`{c}`" for c in sorted(contract.evidence.classes))
                + f"; at least {contract.evidence.documents_demanded}"
                + (
                    ", covering the reporting period."
                    if contract.evidence.must_cover_period
                    else ", not necessarily within the reporting period."
                )
            )
            if contract.evidence.required
            else "None required. The datapoint is optional and unassured."
        ),
        "",
        "## Lawful omissions",
        "",
        *(omissions or ["None. This datapoint has no permitted omission."]),
        "",
        (
            "Anything else that prevents disclosure is an internal failure, not an omission: "
            "the report does not issue, and the reason code says so on the face of the "
            "statement."
        ),
        "",
    ]
    return "\n".join(lines)


def build(root: Path = ROOT) -> dict[Path, str]:
    contracts = loader.load(root)
    files: dict[Path, str] = {CORPUS / "README.md": README}
    for contract in sorted(contracts, key=lambda c: c.id):
        files[CORPUS / f"{contract.id}.md"] = _entry(contract)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the corpus is stale")
    args = parser.parse_args()

    files = build()
    stale: list[str] = []
    CORPUS.mkdir(parents=True, exist_ok=True)

    for path, body in files.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if args.check:
            if current != body:
                stale.append(str(path.relative_to(ROOT)))
        elif current != body:
            path.write_text(body, encoding="utf-8")

    expected = {path.name for path in files}
    for existing in CORPUS.glob("*.md"):
        if existing.name not in expected:
            if args.check:
                stale.append(f"{existing.relative_to(ROOT)} (no contract owns it)")
            else:
                existing.unlink()

    if stale:
        print("the regulatory corpus is out of date:", file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)
        print("run: python pipelines/ingest/regulatory.py", file=sys.stderr)
        return 1

    print(f"regulatory corpus: {len(files)} file(s) for {len(files) - 1} datapoint(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
