"""Governance documents generated from the code that enforces them.

A hand-written control description is a claim about a system. A generated one is a
*projection* of it. The difference shows up six months later, when a threshold moves and the
document does not — and the document is what the auditor reads.

So the reason-code vocabulary, the override rules, the Cedar policy inventory, the contract
register and the retrieval decision are all rendered from their sources, and CI runs the same
renderer with `--check`. Editing one of these files by hand fails the build; changing the code
and forgetting to regenerate fails it too.
"""

from __future__ import annotations

from pathlib import Path

from attestor.contracts import loader, overrides, reason_codes, units
from attestor.contracts.overrides import OverrideEffect
from attestor.policy import cedar
from attestor.policy.tenants import TenantRegistry
from attestor.retrieval import bakeoff, kb

GOVERNANCE_DIR = Path("docs/governance")

_HEADER = (
    "<!-- Generated by `attestor govern generate`. Do not edit by hand: CI regenerates this "
    "file and fails if it differs. -->\n\n"
)


def _abstention_register() -> str:
    lines = [
        _HEADER,
        "# Abstention register\n",
        "Why a figure may go undisclosed, and what each reason does to the report.\n",
        "A contract may pre-authorize only the lawful half. An internal failure blocks the",
        "report and can be lifted only by a signed, expiring override — except one, which",
        "cannot be lifted at all.\n",
        "| code | disposition | effect on the report | basis | overridable to |",
        "|---|---|---|---|---|",
    ]
    for code in sorted(reason_codes.ALL_CODES):
        entry = reason_codes.resolve(code)
        rule = overrides.RULES.get(code)
        if entry.is_lawful:
            effect = "disclosed as an omission"
            override = "—"
        elif rule and rule.is_overridable:
            effect = "**blocks the report**"
            override = ", ".join(sorted(e.value for e in rule.permitted_effects))
        else:
            effect = "**blocks the report**"
            override = "**nothing — this door has no key**"
        lines.append(
            f"| `{code}` | {entry.disposition.value} | {effect} | {entry.basis or '—'} | "
            f"{override} |"
        )
    lines += [
        "",
        "## Override rules",
        "",
        "| code | approvals | roles | maximum duration |",
        "|---|---:|---|---:|",
    ]
    for code, rule in sorted(overrides.RULES.items()):
        if not rule.is_overridable:
            lines.append(f"| `{code}` | — | — | not overridable |")
            continue
        lines.append(
            f"| `{code}` | {rule.approvals_required} | "
            f"{', '.join(sorted(rule.approver_roles))} | {rule.max_duration_days} days |"
        )
    publishable = [
        code
        for code, rule in overrides.RULES.items()
        if OverrideEffect.PUBLISH_WITH_QUALIFICATION in rule.permitted_effects
    ]
    lines += [
        "",
        f"Only {', '.join(f'`{c}`' for c in sorted(publishable))} may be overridden into a "
        "*published* figure, because it is the only internal failure where a figure exists at "
        "all. Everywhere else the override produces a declared omission.",
        "",
    ]
    return "\n".join(lines)


def _contract_register(root: Path) -> str:
    contracts = loader.load(root)
    lines = [
        _HEADER,
        "# Contract register\n",
        f"{len(contracts)} regulated datapoint(s), rendered from `contracts/`.\n",
        "| datapoint | reference | kind | unit | resolver | evidence | lawful omissions |",
        "|---|---|---|---|---|---|---|",
    ]
    for contract in sorted(contracts, key=lambda c: c.id):
        evidence = (
            "inherited"
            if contract.evidence.inherited
            else (
                f"{contract.evidence.documents_demanded}× "
                f"{{{', '.join(sorted(contract.evidence.classes))}}}"
                if contract.evidence.required
                else "not required"
            )
        )
        lines.append(
            f"| `{contract.id}` | {contract.reference} | {contract.kind.value} | "
            f"{contract.unit or '—'} | {contract.resolver.kind} | {evidence} | "
            f"{', '.join(contract.abstention.allowed_reasons) or '—'} |"
        )
    lines += [
        "",
        "## Units in use",
        "",
        "| unit | dimension |",
        "|---|---|",
        *(
            f"| `{unit}` | {units.format_dimension(units.resolve(unit).dimension)} |"
            for unit in sorted({c.unit for c in contracts if c.unit})
        ),
        "",
    ]
    return "\n".join(lines)


def _policy_inventory(root: Path) -> str:
    policies = cedar.load(root)
    registry = TenantRegistry.load(root)
    lines = [
        _HEADER,
        "# Authorization inventory\n",
        f"{len(policies)} Cedar policy(ies) over {len(registry)} tenant(s).\n",
        "| policy | effect | source |",
        "|---|---|---|",
        *(
            f"| `{policy.id}` | {policy.effect.value} | `{policy.source}` |"
            for policy in sorted(policies, key=lambda p: p.id)
        ),
        "",
        "## Tenants",
        "",
        "| tenant | standard | identity | groups claim | namespace |",
        "|---|---|---|---|---|",
        *(
            f"| `{tenant.id}` | {tenant.standard} | {tenant.identity.kind} | "
            f"`{tenant.identity.groups_claim}` | `{tenant.namespace}` |"
            for tenant in sorted(registry, key=lambda t: t.id)
        ),
        "",
    ]
    return "\n".join(lines)


def _retrieval_decision(root: Path) -> str:
    result = bakeoff.run(root, k=3)
    return "\n".join(
        [
            _HEADER,
            "# Retrieval decision\n",
            "Chunking and embedding model are one-way doors. This is the measurement behind",
            "the choice, regenerated from the corpus on every run.\n",
            result.table(),
            "",
            "## Deployed configuration",
            "",
            f"- regulatory: {kb.REGULATORY.describe()}",
            f"- evidence: {kb.EVIDENCE.describe()}",
            "",
            "The vector store is OpenSearch Serverless. A cheaper store would have been",
            "defensible for a system answering a thousand queries a month and indefensible",
            "here: hybrid search is what finds an article by its number, and index-level",
            "metadata filtering is what makes the tenant filter a query constraint rather",
            "than a post-filter over somebody else's rows. Its idle cost is answered by the",
            "estate being ephemeral, not by picking a weaker store.",
            "",
        ]
    )


GENERATORS = {
    "abstention-register.md": lambda root: _abstention_register(),
    "contract-register.md": _contract_register,
    "authorization-inventory.md": _policy_inventory,
    "retrieval-decision.md": _retrieval_decision,
}


def generate(root: Path | str = ".", *, check: bool = False) -> list[str]:
    """Render every governance document. With `check`, report which are stale instead."""
    root = Path(root)
    directory = root / GOVERNANCE_DIR
    directory.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []
    for name, render in GENERATORS.items():
        rendered = render(root)
        target = directory / name
        if check:
            if not target.is_file() or target.read_text(encoding="utf-8") != rendered:
                stale.append(str(target.relative_to(root)))
        else:
            target.write_text(rendered, encoding="utf-8")
    return stale
